export const paymentChannelsSeed = [
  {
    id: 1,
    pgCode: "801",
    pgName: "BNI VA",
    imageUrl: "https://placehold.co/100x50/005E5D/FFFFFF?text=BNI",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 9,
    imageQris: null,
  },
  {
    id: 2,
    pgCode: "800",
    pgName: "BRI VA",
    imageUrl: "https://placehold.co/100x50/00529C/FFFFFF?text=BRI",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 10,
    imageQris: null,
  },
  {
    id: 3,
    pgCode: "802",
    pgName: "Mandiri VA",
    imageUrl: "https://placehold.co/100x50/0033A0/FFFFFF?text=Mandiri",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 7,
    imageQris: null,
  },
  {
    id: 4,
    pgCode: "723",
    pgName: "BSI VA",
    imageUrl: "https://placehold.co/100x50/00A59C/FFFFFF?text=BSI",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 6,
    imageQris: null,
  },
  {
    id: 5,
    pgCode: "825",
    pgName: "CIMB VA",
    imageUrl: "https://placehold.co/100x50/E30613/FFFFFF?text=CIMB",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 8,
    imageQris: null,
  },
  {
    id: 6,
    pgCode: "708",
    pgName: "Danamon VA",
    imageUrl: "https://placehold.co/100x50/FF6F00/FFFFFF?text=Danamon",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 11,
    imageQris: null,
  },
  {
    id: 7,
    pgCode: "408",
    pgName: "Maybank VA",
    imageUrl: "https://placehold.co/100x50/FFB81C/000000?text=Maybank",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 14,
    imageQris: null,
  },
  {
    id: 8,
    pgCode: "402",
    pgName: "Permata VA",
    imageUrl: "https://placehold.co/100x50/00A59C/FFFFFF?text=Permata",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 12,
    imageQris: null,
  },
  {
    id: 9,
    pgCode: "818",
    pgName: "Sinarmas VA",
    imageUrl: "https://placehold.co/100x50/EC1C24/FFFFFF?text=Sinarmas",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 13,
    imageQris: null,
  },
  {
    id: 10,
    pgCode: "718",
    pgName: "BNC VA",
    imageUrl: "https://placehold.co/100x50/00529C/FFFFFF?text=BNC",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 5,
    imageQris: null,
  },
  {
    id: 11,
    pgCode: "812",
    pgName: "OVO",
    imageUrl: "https://placehold.co/100x50/4B0082/FFFFFF?text=OVO",
    isActive: true,
    isRedirect: true,
    vendor: "faspay",
    category: "ewallet",
    sortOrder: 2,
    imageQris: null,
  },
  {
    id: 12,
    pgCode: "302",
    pgName: "LinkAja",
    imageUrl: "https://placehold.co/100x50/ED1C24/FFFFFF?text=LinkAja",
    isActive: true,
    isRedirect: true,
    vendor: "faspay",
    category: "ewallet",
    sortOrder: 4,
    imageQris: null,
  },
  {
    id: 13,
    pgCode: "807",
    pgName: "Akulaku",
    imageUrl: "https://placehold.co/100x50/FFFFFF/000000?text=Akulaku",
    isActive: false,
    isRedirect: true,
    vendor: "faspay",
    category: "va",
    sortOrder: 16,
    imageQris: null,
  },
  {
    id: 14,
    pgCode: "707",
    pgName: "ALFAGROUP",
    imageUrl: "https://placehold.co/100x50/E30613/FFFFFF?text=Alfamart",
    isActive: true,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 15,
    imageQris: null,
  },
  {
    id: 15,
    pgCode: "701",
    pgName: "D-BANK PRO",
    imageUrl: "https://placehold.co/100x50/FF6F00/FFFFFF?text=D-BANK",
    isActive: false,
    isRedirect: false,
    vendor: "faspay",
    category: "va",
    sortOrder: 18,
    imageQris: null,
  },
  {
    id: 16,
    pgCode: "1080011701",
    pgName: "Transfer Muamalat",
    imageUrl: "https://placehold.co/100x50/9900cc/FFFFFF?text=Muamalat",
    isActive: true,
    isRedirect: false,
    vendor: "moota",
    category: "bank_transfer",
    sortOrder: 3,
    imageQris: null,
  },
  {
    id: 17,
    pgCode: "qris",
    pgName: "QRIS",
    imageUrl: "https://4riccmj8v8auvbv7.public.blob.vercel-storage.com/payment-channels/logos/1753080076726-g3jupagzd15.png",
    isActive: true,
    isRedirect: false,
    vendor: "moota",
    category: "qris_statis",
    sortOrder: 1,
    imageQris: "https://4riccmj8v8auvbv7.public.blob.vercel-storage.com/payment-channels/qris/1753089801879-4qph6puya9.jpg",
  },
  {
    id: 18,
    pgCode: "LOKET",
    pgName: "LOKET",
    imageUrl: "https://placehold.co/100x50/000000/FFFFFF?text=LOKET",
    isActive: false,
    isRedirect: false,
    vendor: "moota",
    category: "qris_statis",
    sortOrder: 17,
    imageQris: "",
  },
];
